name = "Blank"
license = "MIT"
licenselink = "https://github.com/EricZhang456/blank/blob/master/LICENSE"
description = "Starter Hugo theme for developers."
homepage = "https://github.com/EricZhang456/blank/"
tags = ["blog", "plain", "blank", "starter", "development"]
features = ["blog"]
min_version = "0.20"

[author]
  name = "Eric Zhang"
  homepage = "https://github.com/EricZhang456"
